# Generated by Django 4.2.10 on 2025-03-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='cycle_hours_at_stop',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='distance_from_last_stop',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='duration_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stop',
            name='stop_type',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('dropoff', 'Dropoff'), ('rest', 'Rest Stop'), ('fuel', 'Fuel Stop')], default='pickup', max_length=10),
        ),
    ]
