# Generated by Django 4.2.10 on 2025-03-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_trip_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
