# Generated by Django 4.2.10 on 2025-03-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_stop_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='current_location',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='dropoff_location',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pickup_location',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
