# Generated by Django 4.2.10 on 2025-03-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_trip_current_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='fuel_stop',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
