# Generated by Django 4.2.10 on 2025-03-26 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_trip_fuel_stop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='current_location_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips_as_current', to='api.location'),
        ),
        migrations.AddField(
            model_name='trip',
            name='pickup_location_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips_as_pickup', to='api.location'),
        ),
        migrations.AddField(
            model_name='trip',
            name='dropoff_location_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips_as_dropoff', to='api.location'),
        ),
        migrations.AddField(
            model_name='trip',
            name='fuel_stop_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips_as_fuel_stop', to='api.location'),
        ),
        migrations.AddField(
            model_name='stop',
            name='location_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='api.location'),
        ),
        migrations.AddField(
            model_name='logsheet',
            name='start_location_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_sheets_as_start', to='api.location'),
        ),
        migrations.AddField(
            model_name='logsheet',
            name='end_location_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_sheets_as_end', to='api.location'),
        ),
    ]
