# Generated by Django 4.2.10 on 2025-03-26 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_swap_location_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='street_name',
            field=models.CharField(default='Unknown Location', max_length=255),
        ),
        migrations.AlterField(
            model_name='stop',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='api.location'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('latitude', 'longitude')},
        ),
        migrations.RemoveField(
            model_name='location',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='location',
            name='title',
        ),
    ]
